install subcommand + --no-install-from-config flag on subcommand

diff --git a/bin/_install/docker b/bin/_install/docker
--- a/bin/_install/docker
+++ b/bin/_install/docker
@@ -5,6 +5,7 @@
 # @parseArger-declarations
 # @parseArger opt config "config file path" --default-value "__home__/.config/MyPi"
 # @parseArger flag use-config "use a config file" --on --no-alias no-config
+# @parseArger flag install-from-config "install from config" --on
 # @parseArger-declarations-end
 
 # @parseArger-utils
@@ -35,6 +36,7 @@ _positionals=();
 _arg_config="__home__/.config/MyPi"
 # FLAGS
 _arg_use_config="on"
+_arg_install_from_config="on"
 _verbose_level="0";
 
 
@@ -49,8 +51,9 @@ print_help()
 	echo -e "	--config <config>: config file path [default: ' __home__/.config/MyPi ']"
 	echo -e "	--use-config|--no-use-config: use a config file, on by default (use --no-use-config to turn it off)
 		no-aliases: --no-config,"
+	echo -e "	--install-from-config|--no-install-from-config: install from config, on by default (use --no-install-from-config to turn it off)"
 	echo -e "Usage :
-	$0 [--config <value>] [--[no-]use-config]";
+	$0 [--config <value>] [--[no-]use-config] [--[no-]install-from-config]";
 	fi
 
 }
@@ -61,28 +64,28 @@ log() {
 	if [ "${_arg_level}" -le "${_verbose_level}" ]; then
 		case "$_arg_level" in
 			-3)
-				_arg_COLOR="[0;31m";
+				_arg_COLOR="\033[0;31m";
 				;;
 			-2)
-				_arg_COLOR="[0;33m";
+				_arg_COLOR="\033[0;33m";
 				;;
 			-1)
-				_arg_COLOR="[1;33m";
+				_arg_COLOR="\033[1;33m";
 				;;
 			1)
-				_arg_COLOR="[0;32m";
+				_arg_COLOR="\033[0;32m";
 				;;
 			2)
-				_arg_COLOR="[1;36m";
+				_arg_COLOR="\033[1;36m";
 				;;
 			3)
-				_arg_COLOR="[0;36m";
+				_arg_COLOR="\033[0;36m";
 				;;
 			*)
-				_arg_COLOR="[0m";
+				_arg_COLOR="\033[0m";
 				;;
 		esac
-		echo -e "${_arg_COLOR}${_arg_msg}[0m";
+		echo -e "${_arg_COLOR}${_arg_msg}\033[0m";
 	fi
 }
 
@@ -107,6 +110,12 @@ parse_commandline()
 				;;
 			--no-use-config|--no-config)
 				_arg_use_config="off"
+				;;
+			--install-from-config)
+				_arg_install_from_config="on"
+				;;
+			--no-install-from-config)
+				_arg_install_from_config="off"
 				;;
 			-h|--help)
 				print_help;
@@ -156,8 +165,7 @@ handle_passed_args_count()
 {
 	local _required_args_string=""
 	if [ "${_positionals_count}" -gt 0 ] && [ "$_helpHasBeenPrinted" == "1" ];then
-		_PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 0 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}').
-	${_positionals[*]}" 1
+		_PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 0 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}').\n\t${_positionals[*]}" 1
 	fi
 	if [ "${_positionals_count}" -lt 0 ] && [ "$_helpHasBeenPrinted" == "1" ];then
 		_PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 0 (namely: $_required_args_string), but got only ${_positionals_count}.
@@ -185,8 +193,9 @@ print_debug()
 	# shellcheck disable=SC2145
 	echo "DEBUG: $0 $@";
 	
-	echo -e "	config: ${_arg_config}";
-	echo -e "	use-config: ${_arg_use_config}";
+	echo -e "\tconfig: ${_arg_config}";
+	echo -e "\tuse-config: ${_arg_use_config}";
+	echo -e "\tinstall-from-config: ${_arg_install_from_config}";
 
 }
 
@@ -210,12 +219,14 @@ trap on_interrupt INT;
 # print_debug "$@"
 # @parseArger-end
 
-log "installing docker" 1;
-curl -sSL https://get.docker.com | sh;
-sudo usermod -aG docker "$USER";
-sudo apt install docker-compose -y;
+if ! [ "$(command -v docker)" ]; then
+	log "installing docker" 1;
+	curl -sSL https://get.docker.com | sh;
+	sudo usermod -aG docker "$USER";
+	sudo apt install docker-compose -y;
 
-# https://superuser.com/a/609141
-# reload groups
-# log "reloading groups for docker, please enter your password" 0;
-exec sudo su -l "$USER";
+	# https://superuser.com/a/609141 comment #1
+	# reload groups
+	# log "reloading groups for docker, please enter your password" 0;
+	exec sudo su -l "$USER";
+fi
